"""HTML import parsing package."""

from parsers.column_aliases import COLUMN_ALIASES, get_mapped_field
from parsers.exceptions import (
    ColumnMappingError,
    EmptyFileError,
    FileTooLargeError,
    ImportLimitExceededError,
    ImportParserError,
    InvalidHtmlError,
    MissingIdentityColumnsError,
    MissingResponseColumnsError,
    MultipleCandidateTablesError,
    NoResponseTableFoundError,
    NoTableFoundError,
    ResponseMappingConflictError,
    UnsupportedFileTypeError,
)
from parsers.html_parser import HtmlImportParser
from parsers.models import (
    ColumnClassification,
    ImportStatistics,
    ParsedColumn,
    ParsedImport,
    ParsedResponse,
    ParsedStudentRow,
    ParsedValidationMessage,
    TableCandidate,
    ValidationSeverity,
)

__all__ = [
    "COLUMN_ALIASES",
    "ColumnClassification",
    "ColumnMappingError",
    "EmptyFileError",
    "FileTooLargeError",
    "ImportLimitExceededError",
    "ImportParserError",
    "ImportStatistics",
    "HtmlImportParser",
    "InvalidHtmlError",
    "MappingValidation",
    "MissingIdentityColumnsError",
    "MissingResponseColumnsError",
    "MultipleCandidateTablesError",
    "NoResponseTableFoundError",
    "NoTableFoundError",
    "ParsedColumn",
    "ParsedImport",
    "ParsedResponse",
    "ParsedStudentRow",
    "ParsedValidationMessage",
    "ReconciliationResult",
    "ResponseMappingConflictError",
    "TableCandidate",
    "UnsupportedFileTypeError",
    "ValidationSeverity",
    "get_mapped_field",
]
